# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'api'
# Original file comments:
# Style guide for Protocol Buffer 3.
# Use CamelCase (with an initial capital) for message names – for example,
# SongServerRequest. Use underscore_separated_names for field names – for
# example, song_name.
#

require 'grpc'
require_relative 'api_pb'

module Api
  module Dgraph
    # Graph response.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'api.Dgraph'

      rpc :Login, ::Api::LoginRequest, ::Api::Response
      rpc :Query, ::Api::Request, ::Api::Response
      rpc :Alter, ::Api::Operation, ::Api::Payload
      rpc :CommitOrAbort, ::Api::TxnContext, ::Api::TxnContext
      rpc :CheckVersion, ::Api::Check, ::Api::Version
    end

    Stub = Service.rpc_stub_class
  end
end
